apiVersion: v1
kind: Namespace
metadata:
  name: stage-train

---

kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
  namespace: stage-train
spec:
  type: NodePort
  selector:
    app: train-schedule-stage
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment-stage
  labels:
    app: train-schedule-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule-stage
  template:
    metadata:
      labels:
        app: train-schedule-stage
    spec:
      containers:
      - name: train-schedule-stage
        image: grocamador/train-schedule:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
