apiVersion: v1
kind: Namespace
metadata:
  name: prod-train

---


kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service-prod
  namespace: prod-train
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30100

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  namespace: prod-train
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
